"""Turning analysis into things a farmer can do this week.

This is the deterministic core of GAIA. The thesis describes a chat interface
backed by an LLM; the reasoning underneath it still has to be something that can
be tested, audited and defended when it tells someone to spend money on lime. So
the recommendations are generated by explicit rules over the estimated state,
each one carrying the evidence that produced it, and the language model - if one
is ever attached - sits on top as a presentation layer rather than as the
decision maker. :func:`as_briefing` is the seam where it would plug in.

Three axes, one per thing the sensor suite can actually see:

**Water** - the estimated root-zone depletion against the crop's allowable
depletion, plus how many days of the current evaporative demand remain before it
gets there.

**Soil pH** - below about 6.0 phosphorus precipitates with iron and aluminium and
stops being available however much fertiliser is applied; below 5.0 aluminium
turns phytotoxic. Coffee wants a lower band than the vegetables, so the
thresholds are per crop.

**Air quality** - the MQ-135 is an uncalibrated qualitative sensor whose
resistance moves with temperature and humidity almost as much as with smoke, and
it cannot tell one gas from another. Comparing it against a published ppm limit
would be false precision. What it *can* do reliably is notice that today looks
nothing like this site's own recent baseline, which is exactly what a burning
event looks like.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import date

import numpy as np
import pandas as pd

from earthguardian.config import Plot

#: Robust standard deviations above a site's own rolling baseline before an air
#: quality excursion is called a burning event.
BURNING_SIGMA = 4.0
#: Consecutive readings required, so a single spike does not raise an alarm.
BURNING_PERSISTENCE = 3
#: Below this state of charge the node will start missing uplinks.
BATTERY_WARNING_PCT = 25.0
#: Aluminium becomes phytotoxic below this pH regardless of crop.
ALUMINIUM_TOXICITY_PH = 5.0


@dataclass(slots=True)
class Advisory:
    """One recommendation, with the evidence behind it."""

    plot_id: str
    axis: str
    severity: str  # "critical" | "high" | "medium" | "info"
    title: str
    finding: str
    action: str
    raised_on: date | None = None
    #: Numbers a sceptical agronomist would ask for.
    evidence: dict[str, float] = field(default_factory=dict)

    def as_dict(self) -> dict:
        payload = {
            "plot_id": self.plot_id,
            "axis": self.axis,
            "severity": self.severity,
            "title": self.title,
            "finding": self.finding,
            "action": self.action,
            "raised_on": str(self.raised_on) if self.raised_on else None,
        }
        payload.update({f"evidence_{k}": v for k, v in self.evidence.items()})
        return payload


_SEVERITY_ORDER = {"critical": 0, "high": 1, "medium": 2, "info": 3}


def rank(advisories: list[Advisory]) -> list[Advisory]:
    """Most urgent first - the order the console and the chat should use."""
    return sorted(advisories, key=lambda a: _SEVERITY_ORDER.get(a.severity, 9))


# --------------------------------------------------------------------------------------
# Water
# --------------------------------------------------------------------------------------


def water_advisory(
    plot: Plot,
    depletion_mm: float,
    raw_mm: float,
    taw_mm: float,
    recent_etc_mm_day: float,
    today: date | None = None,
) -> Advisory:
    """How close the root zone is to the point where the crop starts suffering."""
    fraction = depletion_mm / max(raw_mm, 1e-6)
    headroom_mm = max(raw_mm - depletion_mm, 0.0)
    days_left = headroom_mm / max(recent_etc_mm_day, 1e-6)
    refill_mm = max(depletion_mm - taw_mm * 0.15, 0.0)
    volume_m3 = refill_mm / 1000.0 * plot.area_ha * 10_000 / max(plot.irrigation_efficiency, 1e-6)

    if depletion_mm >= taw_mm * plot.crop_spec.depletion_fraction * 1.35:
        severity, title = "critical", "Crop is losing yield to water stress now"
        action = f"Irrigate today: about {refill_mm:.0f} mm, {volume_m3:.0f} m3 at the meter."
    elif fraction >= 0.9:
        severity, title = "high", "Readily available water is nearly gone"
        action = (
            f"Irrigate within {max(days_left, 0):.0f} day(s): about {refill_mm:.0f} mm "
            f"({volume_m3:.0f} m3). Stop short of field capacity so the next rain has "
            "somewhere to go."
        )
    elif fraction >= 0.6:
        severity, title = "medium", "Approaching the irrigation trigger"
        action = f"Plan to irrigate in about {days_left:.0f} day(s)."
    else:
        severity, title = "info", "Soil water is comfortable"
        action = "No irrigation needed. Next check when depletion reaches 60% of RAW."

    return Advisory(
        plot_id=plot.plot_id,
        axis="water",
        severity=severity,
        title=title,
        finding=(
            f"Root-zone depletion is {depletion_mm:.0f} mm of the {raw_mm:.0f} mm the crop "
            f"can use freely ({fraction:.0%}), against evaporative demand of "
            f"{recent_etc_mm_day:.1f} mm/day."
        ),
        action=action,
        raised_on=today,
        evidence={
            "depletion_mm": round(depletion_mm, 1),
            "raw_mm": round(raw_mm, 1),
            "fraction_of_raw": round(fraction, 3),
            "days_to_trigger": round(days_left, 1),
            "refill_mm": round(refill_mm, 1),
            "volume_m3": round(volume_m3, 1),
        },
    )


# --------------------------------------------------------------------------------------
# Soil pH
# --------------------------------------------------------------------------------------


def ph_advisory(plot: Plot, ph_series: pd.Series, today: date | None = None) -> Advisory | None:
    """Whether the soil chemistry has stopped being the crop's friend."""
    recent = ph_series.tail(30).median()
    if not np.isfinite(recent):
        return None

    crop = plot.crop_spec
    trend = float(ph_series.tail(90).diff().mean() * 30) if len(ph_series) > 90 else 0.0

    if recent < ALUMINIUM_TOXICITY_PH:
        severity = "critical"
        title = "Soil acidity has reached the aluminium toxicity range"
        action = (
            "Lime before the next planting. Below pH 5.0 aluminium attacks root tips "
            "directly, and no amount of water or fertiliser compensates."
        )
    elif recent < crop.ph_min:
        severity = "high"
        title = f"Soil is too acidic for {crop.name.lower()}"
        action = (
            f"Apply lime to bring pH into {crop.ph_min:.1f}-{crop.ph_max:.1f}. Below "
            f"{crop.ph_min:.1f} phosphorus binds to iron and aluminium and stops being "
            "available, so phosphate applied now is largely wasted."
        )
    elif recent > crop.ph_max:
        severity = "medium"
        title = f"Soil is more alkaline than {crop.name.lower()} prefers"
        action = (
            "Check for over-liming. Above the crop's band, iron, manganese and zinc "
            "become hard for the plant to take up."
        )
    else:
        severity = "info"
        title = "Soil pH is in the right band"
        action = f"No action. Recheck at the end of the cycle; the trend is {trend:+.2f} pH/month."

    return Advisory(
        plot_id=plot.plot_id,
        axis="soil_ph",
        severity=severity,
        title=title,
        finding=(
            f"Median pH over the last 30 days is {recent:.2f}; {crop.name.lower()} wants "
            f"{crop.ph_min:.1f}-{crop.ph_max:.1f}. Trend {trend:+.2f} pH per month."
        ),
        action=action,
        raised_on=today,
        evidence={
            "ph_median": round(float(recent), 2),
            "ph_trend_per_month": round(trend, 3),
            "ph_min": crop.ph_min,
            "ph_max": crop.ph_max,
        },
    )


# --------------------------------------------------------------------------------------
# Air quality
# --------------------------------------------------------------------------------------


def detect_burning_events(
    air_quality: pd.Series, timestamps: pd.Series, window: int = 480
) -> list[tuple[pd.Timestamp, float]]:
    """Excursions far above the site's own rolling baseline.

    An absolute threshold is the wrong instrument here. The MQ-135 reports a
    resistance ratio that drifts with temperature, humidity and the sensor's own
    age, and it cannot separate smoke from ammonia off a manure heap. What
    survives all of that is the *shape* of the event: a sharp, sustained
    departure from what this particular sensor has been reading all week.
    """
    values = air_quality.astype(float)
    baseline = values.rolling(window, min_periods=window // 4).median()
    deviation = values - baseline
    scale = 1.4826 * deviation.abs().rolling(window, min_periods=window // 4).median()
    z = deviation / scale.replace(0.0, np.nan)

    flagged = (z > BURNING_SIGMA).fillna(False)
    sustained = flagged.rolling(BURNING_PERSISTENCE).sum() >= BURNING_PERSISTENCE

    events: list[tuple[pd.Timestamp, float]] = []
    previous: pd.Timestamp | None = None
    for index in np.flatnonzero(sustained.to_numpy()):
        when = pd.Timestamp(timestamps.iloc[index])
        if previous is not None and (when - previous) < pd.Timedelta(hours=18):
            continue  # one plume, not many
        events.append((when, float(z.iloc[index])))
        previous = when
    return events


def burning_advisory(
    plot: Plot, events: list[tuple[pd.Timestamp, float]], today: date | None = None
) -> Advisory | None:
    if not events:
        return None
    latest, magnitude = events[-1]
    return Advisory(
        plot_id=plot.plot_id,
        axis="air_quality",
        severity="high" if len(events) > 1 else "medium",
        title="Smoke event detected near the plot",
        finding=(
            f"Air quality departed {magnitude:.1f} robust deviations from this node's own "
            f"baseline on {latest.date()}; {len(events)} such event(s) this season. The "
            "MQ-135 cannot identify the gas, so this is a smoke signature, not a "
            "speciated measurement."
        ),
        action=(
            "Check for burning on or next to the property. Smoke shades the canopy and "
            "deposits ash on leaves; repeated events are also a regulatory exposure."
        ),
        raised_on=today,
        evidence={"events": float(len(events)), "peak_sigma": round(magnitude, 1)},
    )


# --------------------------------------------------------------------------------------
# The node itself
# --------------------------------------------------------------------------------------


def node_advisory(
    plot: Plot, uplinks: pd.DataFrame, expected_per_day: int, today: date | None = None
) -> Advisory | None:
    """Whether the instrument the farmer is trusting is actually healthy."""
    if uplinks.empty:
        return None
    battery = float(uplinks["battery_pct"].tail(96).median())
    days = max(uplinks["timestamp"].dt.floor("D").nunique(), 1)
    delivery = len(uplinks) / max(expected_per_day * days, 1)

    if battery < BATTERY_WARNING_PCT:
        severity, title = "high", "Node battery is running down"
        action = "Check the panel for dust or shading; a flat node stops reporting entirely."
    elif delivery < 0.6:
        severity, title = "medium", "The radio link is dropping a lot of uplinks"
        action = (
            "Consider raising the antenna or moving the gateway. Fewer uplinks means a "
            "coarser water balance and slower detection."
        )
    else:
        severity, title = "info", "Node is healthy"
        action = "No action."

    return Advisory(
        plot_id=plot.plot_id,
        axis="node",
        severity=severity,
        title=title,
        finding=(
            f"Battery {battery:.0f}%, delivering {delivery:.0%} of the "
            f"{expected_per_day} uplinks a day the radio budget allows."
        ),
        action=action,
        raised_on=today,
        evidence={"battery_pct": round(battery, 1), "delivery_ratio": round(delivery, 3)},
    )


# --------------------------------------------------------------------------------------
# Presentation
# --------------------------------------------------------------------------------------


def as_briefing(advisories: list[Advisory], plot: Plot) -> str:
    """A plain-language summary of the ranked advisories.

    This is the seam the thesis's chat interface would sit on. An LLM given this
    briefing can answer questions about it conversationally; what it must not do
    is originate the recommendations, because then nothing above can be tested.
    """
    lines = [f"{plot.farm} - {plot.municipality}/{plot.state}, {plot.crop_spec.name.lower()}"]
    for advisory in rank(advisories):
        marker = {"critical": "!!", "high": "! ", "medium": "- ", "info": "  "}[advisory.severity]
        lines.append(f"{marker} {advisory.title}")
        lines.append(f"     {advisory.finding}")
        lines.append(f"     -> {advisory.action}")
    return "\n".join(lines)
