#!/usr/bin/env python3
"""Capture the console imagery used in the README.

Launches the console, drives it headlessly and saves one still per menu item, so
the visuals hold to the same standard as the numbers: regenerated by a command
rather than screenshotted by hand.

Needs Playwright with Chromium: ``nix develop .#media``, or
``pip install playwright && playwright install chromium``. An installed Chrome
works too, with ``--browser /path/to/chrome``.
"""

from __future__ import annotations

import argparse
import socket
import subprocess
import sys
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
#: The six menu items of the 2024 design, in its order.
PAGES = [
    ("Overview", "console-overview.jpg"),
    ("Fields", "console-fields.jpg"),
    ("Sensors", "console-sensors.jpg"),
    ("Analytics", "console-analytics.jpg"),
    ("Reports", "console-reports.jpg"),
    ("Devices", "console-devices.jpg"),
]
WIDTH, MIN_HEIGHT = 1440, 900


def _free_port() -> int:
    with socket.socket() as sock:
        sock.bind(("127.0.0.1", 0))
        return int(sock.getsockname()[1])


def _wait(port: int, timeout: float = 120.0) -> None:
    deadline = time.time() + timeout
    while time.time() < deadline:
        try:
            with socket.create_connection(("127.0.0.1", port), timeout=1):
                return
        except OSError:
            time.sleep(0.5)
    raise TimeoutError("the console did not come up")


def _settle(page) -> None:
    """Wait for the script run to finish and the charts to draw."""
    page.wait_for_timeout(800)
    page.wait_for_selector('[data-testid="stStatusWidget"]', state="detached", timeout=180_000)
    page.wait_for_load_state("networkidle")
    page.wait_for_timeout(2500)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", type=Path, default=ROOT / "assets")
    parser.add_argument("--browser", help="Chrome or Chromium executable to use instead")
    args = parser.parse_args()

    from PIL import Image
    from playwright.sync_api import sync_playwright

    args.out.mkdir(parents=True, exist_ok=True)
    port = _free_port()
    server = subprocess.Popen(
        [
            sys.executable,
            "-m",
            "streamlit",
            "run",
            str(ROOT / "earthguardian" / "dashboard" / "app.py"),
            "--server.port",
            str(port),
            "--server.headless",
            "true",
        ],
        cwd=ROOT,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
    )
    try:
        _wait(port)
        with sync_playwright() as playwright:
            browser = playwright.chromium.launch(
                executable_path=args.browser, args=["--force-color-profile=srgb"]
            )
            page = browser.new_page(viewport={"width": WIDTH, "height": MIN_HEIGHT})
            page.goto(f"http://127.0.0.1:{port}", wait_until="networkidle", timeout=180_000)
            page.wait_for_selector(".eg-cards", timeout=180_000)

            for label, filename in PAGES:
                page.locator('[data-testid="stSidebar"] label').filter(has_text=label).click()
                _settle(page)
                # The page scrolls inside the app, not the window: grow the
                # viewport to the content so one still holds the whole page.
                height = page.evaluate(
                    "(document.querySelector('[data-testid=\"stMain\"]')"
                    " || document.scrollingElement).scrollHeight"
                )
                page.set_viewport_size({"width": WIDTH, "height": max(MIN_HEIGHT, int(height))})
                page.wait_for_timeout(1500)
                page.mouse.move(WIDTH - 1, 1)

                raw = args.out / "_tmp.png"
                page.screenshot(path=str(raw))
                Image.open(raw).convert("RGB").save(
                    args.out / filename, "JPEG", quality=88, optimize=True
                )
                raw.unlink()
                page.set_viewport_size({"width": WIDTH, "height": MIN_HEIGHT})
                print(f"  wrote {filename}")
            browser.close()
    finally:
        server.terminate()
        server.wait(timeout=30)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
