#!/usr/bin/env python3
"""Capture the console imagery used in the README.

Launches the console, drives it headlessly and saves one still per page, so the
visuals hold to the same standard as the numbers: regenerated by a command
rather than screenshotted by hand.

Needs Playwright with Chromium: ``nix develop .#media``, or
``pip install playwright && playwright install chromium``.
"""

from __future__ import annotations

import argparse
import socket
import subprocess
import sys
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PAGES = [
    ("Fleet", "console-fleet.jpg"),
    ("Soil water", "console-water.jpg"),
    ("Self-calibration", "console-calibration.jpg"),
    ("Radio", "console-radio.jpg"),
    ("Impact", "console-impact.jpg"),
]
VIEWPORT = {"width": 1400, "height": 950}


def _free_port() -> int:
    with socket.socket() as sock:
        sock.bind(("127.0.0.1", 0))
        return int(sock.getsockname()[1])


def _wait(port: int, timeout: float = 120.0) -> None:
    deadline = time.time() + timeout
    while time.time() < deadline:
        try:
            with socket.create_connection(("127.0.0.1", port), timeout=1):
                return
        except OSError:
            time.sleep(0.5)
    raise TimeoutError("the console did not come up")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", type=Path, default=ROOT / "assets")
    args = parser.parse_args()

    from PIL import Image
    from playwright.sync_api import sync_playwright

    args.out.mkdir(parents=True, exist_ok=True)
    port = _free_port()
    server = subprocess.Popen(
        [
            sys.executable,
            "-m",
            "streamlit",
            "run",
            str(ROOT / "earthguardian" / "dashboard" / "app.py"),
            "--server.port",
            str(port),
            "--server.headless",
            "true",
        ],
        cwd=ROOT,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
    )
    try:
        _wait(port)
        with sync_playwright() as playwright:
            browser = playwright.chromium.launch(args=["--force-color-profile=srgb"])
            page = browser.new_page(viewport=VIEWPORT)
            page.goto(f"http://127.0.0.1:{port}", wait_until="networkidle", timeout=180_000)
            page.wait_for_selector("h1", timeout=180_000)
            page.wait_for_timeout(6000)

            for index, (label, filename) in enumerate(PAGES):
                if index:
                    page.get_by_text(label, exact=True).first.click()
                    page.wait_for_timeout(1200)
                page.wait_for_load_state("networkidle")
                page.wait_for_timeout(3500)
                page.mouse.move(VIEWPORT["width"] - 1, VIEWPORT["height"] - 1)
                page.wait_for_timeout(300)

                raw = args.out / "_tmp.png"
                page.screenshot(path=str(raw))
                Image.open(raw).convert("RGB").save(
                    args.out / filename, "JPEG", quality=88, optimize=True
                )
                raw.unlink()
                print(f"  wrote {filename}")
            browser.close()
    finally:
        server.terminate()
        server.wait(timeout=30)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
